import { Alert, Button, Form, Input, Select, Space } from 'antd';

// The zod schema (generated by Orval from the OpenAPI spec) is used here only as
// the *source of the field limits*, translated into native Antd rules by
// `antdRulesFromZod`. Antd Form still performs validation — zod never runs at
// validation time (see CLAUDE.md + antd-zod-rules.ts).
import { AddPetBody } from '@/api/generated/zod/pet/pet.zod';
import type { PetStatus } from '@/entities/pet';
import { antdRulesFromZod } from '@/lib/antd-zod-rules';

export type AddPetFormValues = {
  name: string;
  category: string;
  status: PetStatus;
};

interface AddPetFormProps {
  onSubmit: (values: AddPetFormValues) => Promise<void>;
  isLoading: boolean;
  error?: string | null;
  onCancel?: () => void;
}

const options: { value: PetStatus; label: string }[] = [
  {
    value: 'available',
    label: 'available',
  },
  {
    value: 'pending',
    label: 'pending',
  },
  {
    value: 'sold',
    label: 'sold',
  },
];

// Derived once from the generated schema — the `name` field's required-ness
// comes straight from the OpenAPI contract and stays in sync with it.
const petRules = antdRulesFromZod(AddPetBody);

export function AddPetForm({ onSubmit, isLoading, error, onCancel }: AddPetFormProps) {
  const [form] = Form.useForm<AddPetFormValues>();
  const handleSubmit = async () => {
    let values: AddPetFormValues;
    try {
      values = await form.validateFields();
    } catch {
      return;
    }

    await onSubmit(values);
  };

  return (
    <Space orientation='vertical' style={{ width: '100%' }} size='large'>
      {error && <Alert type='error' title={error} showIcon />}
      <Form<AddPetFormValues> form={form} layout='vertical' aria-label='Add pet'>
        {/* Rules derived from the generated zod schema (the spec marks `name`
            required). */}
        <Form.Item name='name' label='Name' rules={petRules.name}>
          <Input />
        </Form.Item>
        {/* `category` and `status` are optional in the petstore spec, but this
            form requires them as a page-level UX choice ("pages first" —
            CLAUDE.md), so their rules stay local rather than schema-derived. */}
        <Form.Item
          name='category'
          label='Category'
          rules={[{ required: true, message: 'Category is required' }]}
        >
          <Input />
        </Form.Item>
        <Form.Item
          name='status'
          label='Status'
          rules={[{ required: true, message: 'Status is required' }]}
        >
          <Select options={options} />
        </Form.Item>

        <Form.Item style={{ marginBottom: 0 }}>
          <Space style={{ width: '100%', justifyContent: 'flex-end' }}>
            <Button onClick={onCancel}>Cancel</Button>
            <Button type='primary' onClick={handleSubmit} loading={isLoading}>
              Save
            </Button>
          </Space>
        </Form.Item>
      </Form>
    </Space>
  );
}
